### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by martin159** [MultiTricker/TMEP#3]
Dobry den,
bylo by mozne k projektu pridat licencni soubor (napr. casto pouzivany `LICENSE.TXT`)? I kdyz TMEP pouzivam na webu k Papouch teplomeru, stale si nejsem jisty, jestli neporusuji nejaka Vase prava. 
Jednouchy soubor se zminkou o Komercni/Freeware/GPL/... by to rychle vyjasnil.

Dekuji.

**Comment by MultiTricker** [comment]
Hezký den,

budu teď dva týdny mimo, ale potom se podívám, co by projektu nejvíce vyhovovalo a doplním. V podstatě mi jde o zachování open source s odkazem na původní projekt a autora, jinak úpravy libovolné.

Díky za podnět.

**Comment by MultiTricker** [comment]
Licenci CC BY-NC-SA 4.0 jsem zatím dal do textu popisu aplikace. Nejsem si úplně jistý, jak to správně napsat, aby byla respektovaná licence pro HighCharts a jQuery, ale věřím, že takto je to pohromadě napsané správně.
