### ISSUE TITLE
Tlak vzduchu

### ISSUE THREAD

**Issue by tuxmartin** [MultiTricker/TMEP#4]
Dobry den,
planujete pridat do aplikace podporu mereni tlaku vzduchu? Zvlast ve spojeni s Arduinem by se to hodilo.

Diky za info.

**Comment by MultiTricker** [comment]
Hezký den,

v plánu to nemám. To bych raději udělal univerzální řešení, když už (pro libovolná měření), ale na to se také nechystám (právě z časových důvodů).

Díky za zájem.
