### ISSUE TITLE
Multi-sensor

### ISSUE THREAD

**Issue by ppmim** [MultiTricker/TMEP#5]
How could be added additional sensors ? I think it would be an interesting feature.

**Comment by MultiTricker** [comment]
Indeed, but I have no time to expand TMEP like that for everyone (make administration interface, cover scenarios of what could happend...).

I do offer hosted TMEP for more sensors on http://www.tmep.cz, but interface is in Czech.

So no solution for more sensors in near future. If you would like to have more sensors, you need to install more instances of TMEP.
